### ISSUE TITLE
'b' Build Script assumes Stack is being used even if Cabal is selected as the only option to be added.

### ISSUE THREAD

**Issue by ShiningTrapez** [kowainik/summoner#133]
Seems to be defined here : https://github.com/kowainik/summoner/blob/5658df787f426a594d39539a1ce7ceb02ebeebad/src/Summoner/Template.hs#L644

Might be a little more difficult than just mapping the equivalent Cabal Commands as Cabal Sandboxes need to be considered. I'm also not that familiar with Cabal (I assume the sequence of commands will be something along the lines of `cabal new-update`, `cabal new build $$args --<opts>` but I'm not sure what the exact commands actually would be so advice would be appreciated for writing a PR for this.)

**Comment by ChShersh** [comment]
@ShiningTrapez Thanks for your feedback! It's true that mapping between `stack` and `cabal` commands is not that simple. But `b` script probably will be removed eventually in the next release. This idea was discussed under this issue:

* https://github.com/kowainik/summoner/issues/27

The purpose of `b` script is to colorize error message and remove long paths from building modules. It uses some `perl` magic to achieve this. But this is no longer relevant since GHC-8.2.2 can all these things. So there's no much sense in having `b` script at all.
