### ISSUE TITLE
Add `.nix` file to `summoner` as well

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#150]
I assume it's content should be consistent with issue #149

**Comment by mgttlinger** [comment]
Given that my current workflow of copying and modifying my nix files for each new Haskell project is rather cumbersome I would be interested in working on this issue. 

Where should I look in the source to get up to speed and what exactly shall be generated?

**Comment by ChShersh** [comment]
@mgttlinger This issue is about adding `.nix` file to the `summoner` GitHub repo and, preferably, patch `.travis.yml` to build with `nix` on CI and add instructions how to build with `.nix` or what should be done to update configuration and when `.nix` configuiration requires update. For teaching `summoner` to generate `.nix` files, see issue #149

**Comment by mgttlinger** [comment]
Oh, then I misunderstood. But I#d be interested in doing both.

**Comment by chessai** [comment]
I have something that generates a nix config for a project that works, will have a PR shortly

**Comment by chessai** [comment]
i imagine the PR will need some review, i'm very unfamiliar with travis

**Comment by ChShersh** [comment]
@chessai This looks very nice! And it would very kind of you to give some short description to every file and why it's needed :slightly_smiling_face: I would like `summoner` to be beginner-friendly tool, that's why description and comments are valuable! For example, how users can build with different GHC versions using `nix` and so on. I'm not using `nix`, so I'm not aware of the workflow... But if there're simple build command, this can help to modify `.travis.yml` as well to build with nix on CI and test there. So this is useful not only for beginners :smile:

**Comment by chessai** [comment]
@ChShersh understood
