### ISSUE TITLE
AppVeyor only with Stack

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#171]
We shouldn't create the `appveyor.yml` file if it's only Cabal project (also shouldn't ask during the interactive process).

**Comment by Simeon979** [comment]
This was the behaviour I observed when testing. Do you mean it behave differently on windows?

**Comment by Simeon979** [comment]
Yeah, and that was what happened when I tried it. When I answered ```n``` for addition of stack, I wasn't prompted for addition of AppVeyor, just ```AppVeyor CI integration won't be added to the project```

**Comment by ChShersh** [comment]
@vrom911 @Simeon979 Ah, I see. I looked closely at the code. So when we ask for the AppVeyor settings we actually check whether it's `cabal`-only project:

https://github.com/kowainik/summoner/blob/440b5edd0e302de927e185f941e0d344a95ad970/src/Summoner/Project.hs#L50

But when we generate file via template, we check only `appVey` variable:

https://github.com/kowainik/summoner/blob/440b5edd0e302de927e185f941e0d344a95ad970/src/Summoner/Template.hs#L54

This works now, because value of `appVey :: Bool` is calculated only once and used only once. But this value depends on the value of `stack` boolean flag. We have plans to patch the UI of `summoner` and this patching will result into need to have this check in multiple places. I would like to have this check only in a single place, but it's not clear to me, how to refactor boolean flags to specify dependencies between them only once in a single place.

I think that this issue can be closed for now (since it's already resolved) but there's still something to think about and to discuss.

**Comment by vrom911** [comment]
Oh, sorry, thanks for a good catch, @Simeon979 !
I'm closing this 🙂
