### ISSUE TITLE
Make list of GHC versions `NonEmpty`

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#179]
List of GHC versions actually never can't be empty. So let's make it `NonEmpty`:

* https://github.com/kowainik/summoner/blob/0a533d01bf1800a4fbe1323f40efdb66a8bbae0b/src/Summoner/Settings.hs#L33

**Comment by StevenXL** [comment]
I'll take a stab at it!

**Comment by StevenXL** [comment]
I forgot to mention that in `Project.hs`, I use `fromList`, which is a partial function, but since the list will always have, at a minimum, the default GHC version, I felt this was OK. If we wanted to, we could use  [try](https://www.stackage.org/haddock/lts-12.14/base-4.11.1.0/Control-Exception.html#v:try) since we are already in the IO monad.

**Comment by ChShersh** [comment]
Closed in #183 due to reasons started from this comment:

* https://github.com/kowainik/summoner/pull/183#issuecomment-434916360
