### ISSUE TITLE
Remove `b` script

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#27]
As it seen at the screenshot coloring is not working as it should at the `ghc 8.2.1`:
![image](https://user-images.githubusercontent.com/8126674/31460697-e8ec63aa-aecf-11e7-8ce8-fe566fd2fb39.png)

**Comment by ChShersh** [comment]
The coloring should be disabled for GHC >= 8.2.1. But also this should be added to `stack.yaml`:

```yaml
ghc-options:
  "$locals": -fhide-source-paths
```

**Comment by ChShersh** [comment]
Okay, I propose to do the following with this `b` script:

1. It makes sense only for older GHC and for multi-package projects. I think nobody cares about pretty output for GHC < 8.2.1 because such old GHCs are the default nowadays for creating new project.
2. We should add "$locals" to every `stack.yaml` file.
3. We should remove coloring from `b` script.
