### ISSUE TITLE
Add example Cabal and Stack projects

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#281]
For the moment we have [Full Cabal & Stack project](https://github.com/kowainik/summoner/tree/1bd275d6b31040851126e779395ace3e1ab6fa19/summoner-cli/test/golden/fullProject) which is used for golden tests. It would be handy to have Stack project and Cabal project separately to use them as examples.

Also, probably it makes sense to move them under `~/examples/` folder.

**Comment by ChShersh** [comment]
This is a nice idea! More tests and more examples! So people can immediately see what will be generated. And we also will have more robust tests. I also like the idea of moving this into `examples/` directory :+1:

**Comment by ChShersh** [comment]
This is a big and tedious task. I agree with @vrom911 that we should have the `examples/` directory. And I see the following examples.

1. Minimal cabal-only project with everything disable as possible.
2. Only cabal project (travis + appveyor + relude + etc.)
3. Only stack project (travis + appveyor + relude + etc.)
4. Both builds tools enabled with all features used.

I think that this will show different examples. And also will increase our test coverage by a lot.

Also, I think that probably this should be done after we migrate to `cabal-2.4` and common stanzas because if we implement all examples now, we will spend more time changing our tests in future...
