### ISSUE TITLE
RFE: configuration for default Cabal version

### ISSUE THREAD

**Issue by juhp** [kowainik/summoner#312]
It would be nice to have a configuration variable for the default Cabal version.
Personally I am not planning to enforce Cabal 2.0 in my projects yet - maybe before Cabal 3 is released.

**Comment by vrom911** [comment]
This would be problematic as you know that different versions of the Cabal have the different syntax of `.cabal` file. And we actually do use the features related to the version `2.0`, so the generated package won't build if you only change the Cabal version in the `.cabal` file. Some more work should be done to achieve that. And it's extremely difficult to test that.

Also, as we are planning to move to `2.4` (see #246) it would become way too problematic to keep all possible options of Cabal versions and additional modifications that would need to be done in many other parts of the project. However, this is not the problem as both Stack and Cabal support version `2.4`.

Also, keep in mind that at the moment if you use Stack, it would still force you to use the Cabal version that comes with the GHC. So if you're using the default GHC you still need to use newer Cabal version. We already had to give up the old GHC versions to be tested at CI with Stack because of these reasons (see discussions under this PR #279, there are also links to Stack ticket).

**Comment by juhp** [comment]
Okay, fair enough...
