### ISSUE TITLE
use haskell-ci for generated ci files?

### ISSUE THREAD

**Issue by chessai** [kowainik/summoner#358]
haskell-ci has gotten really good for automating travis configs (idk about other things, but i know it works very well for travis). haskell-ci works for all my haskell projects out-of-the-box, without me needing to edit anything, whereas i have never had such luck with the summoner automatically-generated travis.yml.

again, this could apply to other ci, but as far as github, i only use travis.

thanks

**Comment by vrom911** [comment]
> I have never had such luck with the summoner automatically-generated travis.yml.

Could you show the actual issues you had with that? It works 100% times for my use cases, so it would be much helpful to produce the problems you encounter as we really don't know. We do appreciate bug reports though.

Regarding `haskell-ci`, I was first thinking about using it back when I just started working on `hs-init`, but it had some limitations I couldn't deal with. At the moment, I primarily would be voting against adding the requirement for another tool to be installed in order to use `Summoner`. We want to keep it independent (in the way we can afford it). Another thing is that as we are supporting Cabal and Stack equally for the project generation, it becomes a problem for `haskell-ci`, while we are dealing with such case with our small config. Moreover, I would say, the produced by `haskell-ci` config is not that clear and easy to read through. This also makes a big difference for us. Not to mention, that we are supporting Travis specific features such as `HLint` check or `-Werror` (for Stack).

Additionally, I would like to mention that `Travis` is the opt-in choice on purpose. You can always generate `.travis.yml` files with other external tools. We mostly focused on the simplicity and maintainability, and, I hope that you can agree here, [48-lines config](https://github.com/kowainik/membrain/blob/master/.travis.yml) that provides the support of 4 latest major GHC versions on two build tools with the HLint check as well is quite elegant. You may probably be interested in [the blog post](https://kodimensional.dev/posts/2019-02-25-haskell-travis) by @chshersh  in which he describes the choices in the config better.

**Comment by vrom911** [comment]
Hey @chessai , sorry for bothering. Do you mind sharing the problematic config? I really would love to help but with the lack of the context it makes it not possible to do at the moment :disappointed:

**Comment by chessai** [comment]
Oh, I'm sorry. I read this but was busy at the time. I do not have the problematic config. Maybe this issue should just be closed, since no one else seems to have an issue with it.

**Comment by vrom911** [comment]
I will close it for now as it seems that you are not going to share the issue it's failing with, so we can't do a lot due to the lack of information.. That's okay, however, feel free to reopen or create a new one when you could provide a bit more details on the problem. We are willing that this could work for everyone, so this case is particularly interesting for the project!
