### ISSUE TITLE
Replace `curl` with a Haskell library

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#392]
Currently, we are using `curl` tool to download by URL:

* LICENSE
* Custom files under `files.url`

We can instead use recently released Haskell library [downloader](http://hackage.haskell.org/package/downloader) to download files over HTTPS. This library is lightweight, and we can remove a dependency from an external tool. Also, we will have better control over error messages.

**Comment by patrickt** [comment]
FWIW `downloader` depends on a `curl` installation being present, so that dependency is still present, albeit indirectly. Abstraction doesn’t hurt in this case, though.

**Comment by chshersh** [comment]
@patrickt Thanks for the information and feedback! We need to think more about the switch in that case. 
The main benefit I would like to have is not depending on the `curl` tool. If `downloader` still uses `curl` underhood then utilising this library, when we don't have a lot of control over it, might not worth it. I was also thinking about `http-client-tls`, but it's a very heavyweight library (in terms of Haskell dependencies), and we care about Haskell dependencies footprint especially when users will install Summoner from sources.

**Comment by patrickt** [comment]
As far as pure-Haskell solutions go, I’ve had success with [`http-io-streams`](http://hackage.haskell.org/package/http-io-streams).

**Comment by hasufell** [comment]
> http-client-tls

Before you use something like that, please be aware of the state (and attitude) of haskell TLS: https://github.com/vincenthz/hs-tls/issues/117

**Comment by willbasky** [comment]
Hey!
Any idea which library better at the end?

**Comment by hasufell** [comment]
@willbasky [don't use haskell-tls](https://mail.haskell.org/pipermail/libraries/2020-August/030671.html), use bindings to openssl. There are two afaik:

* http://hackage.haskell.org/package/http-io-streams maintained by Herbert
* http://hackage.haskell.org/package/http-client-openssl maintained by Snoyman

Those are both excellent maintainers. The problem is that you have to deal with SSL context initialization yourself (and possibly various [other issues](https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/8)). You can see a downloader implementation for http-io-streams [here](https://gitlab.haskell.org/haskell/ghcup-hs/-/blob/master/lib/GHCup/Download/IOStreams.hs) and one for http-client-openssl [here](https://gitlab.haskell.org/haskell/ghcup-hs/-/blob/dd72f1eeaf1bb63cfbfdaab5e68b275e73255ca8/lib/GHCup/Download/Internal.hs). However, it's hard to beat tools like `curl` doing all the work for you.

Invoking curl (the binary) is currently the most cross-platform, robust and secure way to download things. If you statically link, you're potentially exposing your users to an outdated SSL library. `cabal-install` also invokes curl the binary and falls back to wget.

**Comment by chshersh** [comment]
@hasufell Thanks for your insights and additional info!

I tend to close this issue. The solution with `curl` works great for us as far, and nowadays `curl` is usually present on each system. We also don't want to introduce too many heavy dependencies to Summoner... So, if there's no lightweight and robust library for downloading files, I guess I can close this issue for now, and reopen if something interesting occurs.
