### ISSUE TITLE
Support 'hpack'

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#40]
There's a lot of hype around `hpack`. Maybe it's a good idea to add support for it in `hs-init` :)
With separate flag, I guess, `-h`. It's not busy currently as I can see...

**Comment by vrom911** [comment]
Well, I also heard this proposal long ago. I don't mind supporting it, but certainly we don't want to give up `stack` :)

**Comment by ChShersh** [comment]
Yeah, we don't have defaults in `hs-init`. So this option can be either disabled or enabled with CLI otherwise should be asked interactively.

**Comment by ChShersh** [comment]
We're not planning to support `hpack` at the moment. Reasons are described here: https://github.com/kowainik/summoner/pull/94#issuecomment-396447512

**Comment by vrom911** [comment]
After some discussions, I guess we can do something with this. I still don't think that we should take responsibility for other tools (or rewrite them), so I propose just to reuse the other tools. In this particular case we can use `hpack-convert`.

As @ChShersh found out, there is an easy way of checking whether the executable in the PATH or no. Because of this I think we can add `hpack` option and config field which when turned on will check whether user have `hpack-convert` or not and run it on the generated project. If it's not in the PATH nothing should be done (in TUI `hpack` checkbox should be disabled then).

@adituv @ChrisPenner what do you think about this solution? Do you think that it can be helpful?

**Comment by ChrisPenner** [comment]
Sounds very reasonable to me! Maybe a warning should be printed if you have `hpack` turned on in your config file but don't have the `hpack-convert` installed.

So glad that this is being considered, thanks for taking a second look at it!

Cheers!

**Comment by vrom911** [comment]
It seems like `hpack-convert` is not supported anymore :( Sorry to bring this, but looks like the option with looking for this executable is not considered anymore.

Also, I want to mention some good news: Summoner currently supports [common stanzas](https://vrom911.github.io/blog/common-stanzas), which could probably solve the problem of the need in `hpack` in the first place.

As we discussed before, to support `cabal` to `hpack` converter inside the Summoner is not a reasonable thing to do. That brings me to the conclusion that we currently won't be able to support Hpack tool the same way we won't support any other substitute for `cabal` file format. I still think that this is out of the scope of this tool and can be a separate complete project. This just doesn't align with the plans for further development plans for Summoner.

Closing this issue because of the described difficulties. In case we come up with some reasonable solution to the problem of bringing hooks to summoner we can open a separate issue for that.
