### ISSUE TITLE
Rerecord demo videos

### ISSUE THREAD

**Issue by vrom911** [kowainik/summoner#423]
To show all the improvements and new features.
See https://github.com/kowainik/summoner/wiki/Asciinema-recording for inspiration.

**Comment by chshersh** [comment]
@vrom911 Great idea 👍 I guess we can also update wiki a little bit, since the config format has changed and we've added some more features.

Also, should we update screenshot with TUI screen sections? We've added GitHub actions checkbox to it, but I don't know whether it's worth redoing the screen only because of that...

* https://github.com/kowainik/summoner#tui-

**Comment by vrom911** [comment]
I think it worth it, especially, it's not that much effort from us :paintbrush:
