### ISSUE TITLE
Generating hie.yaml files in summoner?

### ISSUE THREAD

**Issue by patrickt** [kowainik/summoner#451]
Though I use summoner to generate all my projects, I find myself copy-and-pasting `hie.yaml` files ([reference](https://github.com/mpickering/hie-bios/blob/master/README.md)) between projects so that I can set up `cradle` stanzas to keep my editor tooling working. Would anyone else be interested in the ability to generate a `hie.yaml` with its components already set up appropriately?

**Comment by chshersh** [comment]
Hi @patrickt, thanks for the idea. However, with Summoner, you already can specify custom files to add to your project during scaffolding. You can find an example here:

* https://github.com/kowainik/org/blob/02688a958d13cce857dde1de1e9f82d37dfff2b3/.summoner.toml#L17-L24

Instead of `url` you can use either `local` to specify the path to a local file or `raw` to specify the raw content of the file. So, if you want to automatically copy-paste `hie.yaml` to your new projects, you can add something like this in your `.summoner.toml` configuration:

```toml
files =
    [ { path = "hie.yaml"
       # use URL field
      , url  = "<URL to hie.yaml>"
      # or path field
      # path = "/path/to/local/hie.yaml"
      # or raw field
      # raw = "cradle: ..."
      }
    ]
```

Also, it seems arbitrary and a bit unfair to support and promote only one specific IDE instead of some another or all of them (and supporting all of them is almost impossible). In Summoner, we strive to be non-opinionated. And finally, I'm not using HIE personally, so I'm afraid that this feature may become broken without extra care and additional testing during each release.

**Comment by patrickt** [comment]
Makes sense! Thanks for the detailed explanation.

**Comment by andys8** [comment]
@chshersh Could you elaborate this?

> Also, it seems arbitrary and a bit unfair to support and promote only one specific IDE instead of some another or all of them (and supporting all of them is almost impossible)

My understanding is that haskell-ide-emgine to as deprecated and ghcide and haskell-language-server both need an `hie.yaml` file to work (haskell-language-server using ghcide). Do you have other/more "IDEs" in mind?

Regarding the topic (and if it's considered):

Would the generated `hie.yaml` be different depending on the configuration? Then https://hackage.haskell.org/package/implicit-hie could work. Otherwise a static hie.yml file would do the job.

**Comment by chshersh** [comment]
@andys8 Other Haskell IDEs include:

* Intellij IDEA
* Atom
* Sublime
* Various modes for Vim/NeoVim/Emacs/Spacemacs/Dante
* Different plugins for VSCode
* Leksah
* And probably something else!

Some of these IDEs may work only with Cabal or Stack. At least knowing this fact and checking it requires a lot of overhead 🙂 

Nevertheless, the team behind HLS pushes a lot to improve it, and it's becoming better and better with days. So, I guess, it makes sense to generate the `hie.yaml` by default, if it requires some customization (or maybe add a config option?).

@patrickt @andys8 Could you provide the content of `hie.yaml` for Cabal-only and Stack-only project with the library, executable, test-suite and benchmark and verify, whether it's different from what `implicit-hie` does?

cc @Avi-D-coder, you might be interested in this conversation as well or help to clarify the behaviour of `implicit-hie` 🙂
