### ISSUE TITLE
Add default test-suite implementation

### ISSUE THREAD

**Issue by ChShersh** [kowainik/summoner#83]
We already have dummy benchmarks with `gauge` library. I would like to have summy test-suite with `tasty`, `tasty-discover`, `hedgehog` and similar stuff. Probably not everyone likes such stack of testing libraries. So we should think on how to make this configurable and convenient...

**Comment by ChShersh** [comment]
@vrom911 I agree. Looks like more time can be spent on thinking about and implementing proper configuration format for testing library selection than on whole previous `summoner` work... I'm okay with closing this for now to clean up some issue. Can reopen it later. Also, GitHub now has feature of issue suggestions so this issue is likely to pop up when somebody will try to create similar issue :slightly_smiling_face:

**Comment by avh4** [comment]
I came across this when trying to create a new project today.  My could preference would be to have an option for `tasty`, with `tasty-hspec` and `tasty-discover`, and an example passing test.

**Comment by chshersh** [comment]
@avh4 I can see how this can be beneficial for many people, but in Summoner we strive not to be opinionated and give preference to some libraries and tools. So, it's either all or nothing. And supporting all testing library is a nightmare... Partially, due to these reasons, we removed `gauge` from benchmarks in the recent release. Maybe in some future, some sort of plugin or extension system will be implemented, but there's no such thing at the moment 🙂

**Comment by avh4** [comment]
Ah, thanks.  I missed that the gague example had been removed.

My real goal is to find a quick way to get folks started with a new haskell project that supports modern practices.  I just created a thread here to further that discussion if anyone know of more opinionated project scaffold tools or wants to share what testing configuration they'd prefer in a new project: https://discourse.haskell.org/t/what-are-existing-batteries-included-project-scaffolds/1484
