### ISSUE TITLE
Add 'warnings' field to configuration

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#91]
There're some warnings which are not included in `-Wall` but some people think they should be used anyway. I think we should create special configuration field for this. And add some fields to our default config.

Source:

* https://www.reddit.com/r/haskell/comments/6q9tcp/ghc_warnings_you_should_use_in_addition_to_wall/

Comments are interesting as well.

**Comment by ChShersh** [comment]
@willbasky This task is about only adding `warnings` fields to configuration. You should this extra field to configuration here:

https://github.com/kowainik/summoner/blob/96b10338c4296c2363913f15236ea49a602b14f0/src/Summoner/Config.hs#L45-L65

And then you should use it to populate `ghc-options` field in `.cabal` files.

**Comment by willbasky** [comment]
Will warnings add to configuration if there is `--file conf.toml` or\and if _yes_ in interactive mode?

**Comment by ChShersh** [comment]
@willbasky We have this note in README about priority order:

* https://github.com/kowainik/summoner#usage

But personally I think that it doesn't make much sense to ask about warnings interactively. We already add `-Wall` by default and this should be enough in 99.9% cases. For those who want extra warnings, it's better to specify them in configuration because names on warnings are very long. And it's not convenient to type them manually. So I expect that nobody will write warnings in interactive mode.

But I think that it's a good idea to be able to specify them through CLI options.

**Comment by willbasky** [comment]
I agree with you. If someone will want to change warnings it easy to rewrite them in text mode after project created.

**Comment by vrom911** [comment]
I don't entirely agree about CLI part. I guess it's almost the same as with pragmas, better to use config files for that.

**Comment by ChShersh** [comment]
@vrom911 Yeah, that makes sense as well. Probably it's better to not allow them as CLI as well.
